# Generated by Django 6.0.4 on 2026-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_option_a_question_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text="Gap Fill bo'lsa: to'g'ri so'zni yozing. MCQ bo'lsa: to'g'ri variant harfini yozing (A, B, C yoki D).", max_length=255),
        ),
    ]
