# Generated by Django 6.0.4 on 2026-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0002_practicequestion_practicesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='table_config',
            field=models.JSONField(blank=True, help_text='Headers and Rows as JSON', null=True),
        ),
        migrations.AddField(
            model_name='practicesubmission',
            name='table_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='question_type',
            field=models.CharField(choices=[('image', 'Image Submission'), ('text', 'Text Submission'), ('table', 'Table Submission')], max_length=10),
        ),
    ]
