# Generated by Django 6.0.4 on 2026-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0006_creativetask_creativetasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativetasksubmission',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='creativetasksubmission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Baholash (Ball)'),
        ),
        migrations.AddField(
            model_name='practicesubmission',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='practicesubmission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Baholash (Ball)'),
        ),
        migrations.AddField(
            model_name='seminarsubmission',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='seminarsubmission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Baholash (Ball)'),
        ),
        migrations.AddField(
            model_name='seminartablesubmission',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='seminartablesubmission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Baholash (Ball)'),
        ),
        migrations.AddField(
            model_name='tablesubmission',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='tablesubmission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Baholash (Ball)'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Baholash (Ball)'),
        ),
    ]
