# Generated by Django 6.0.4 on 2026-04-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0008_seminar_seminarquestion_seminar_seminartable_seminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='moduls.practicetopic'),
        ),
        migrations.AddField(
            model_name='tablepractice',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='moduls.practicetopic'),
        ),
    ]
